### PR TITLE
current code

### PR DESCRIPTION
**Pull request by ariovistus**

### CODE REVIEW

**Comment by ariovistus** [comment]
spark is out, victor is in, "maybe" sounds like "unvetted design" to me, and the extra states exist whether you want to acknowledge them or not, though that's kind of irrelevant to code structure.

Your FSM code is better than mine was, though.

**Comment by ariovistus** [comment]
well, except for your using a switch statement

**Comment by bb010g** [comment]
Sorry. My shooter additions were written in ~40 minutes (including figuring out the current code) before I had to go, so they were rather untested. :( I'm fine with changing them and would love to do more hardware tests on Wooden Dragon.

**Comment by ariovistus** [comment]
me too

**Comment by ariovistus** [comment]
robot name on thebluealliance is chips again

**Comment by bb010g** [comment]
The Blue Alliance pulls from TIMS IIRC. Bug Booth.

**Pull request merged**
